#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <Path/Path.h>
#include <D2BasicTypes.h>


BEGIN_VISIT(D2CoordStrc)
	FIELD(nX)
	FIELD(nY)
END_VISIT()

BEGIN_VISIT(D2PathPointStrc)
	FIELD(X)
	FIELD(Y)
END_VISIT()

BEGIN_VISIT(D2FP32_16)
	FIELD(wOffsetX)
	FIELD(wPosX)
	FIELD(wOffsetY)
	FIELD(wPosY)
END_VISIT()

BEGIN_VISIT(D2DynamicPathStrc)
	OBJECT(tGameCoords)
	FIELD(dwClientCoordX)
	FIELD(dwClientCoordY)
	OBJECT(tTargetCoord)
	OBJECT(tPrevTargetCoord)
	OBJECT(tFinalTargetCoord)
	POINTER(pRoom)
	POINTER(pPreviousRoom)
	FIELD(dwCurrentPointIdx)
	FIELD(dwPathPoints)
	OMIT(unk0x2C)
	POINTER(pUnit)
	FIELD(dwFlags)
	FIELD(unk0x38)
	FIELD(dwPathType)
	FIELD(dwPrevPathType)
	FIELD(dwUnitSize)
	FIELD(dwCollisionPattern)
	FIELD(nFootprintCollisionMask)
	FIELD(nMoveTestCollisionMask)
	FIELD(nCollidedWithMask)
	FIELD(padding0x56)
	POINTER(pTargetUnit)
	FIELD(dwTargetType)
	FIELD(dwTargetId)
	FIELD(nDirection)
	FIELD(nNewDirection)
	FIELD(nDiffDirection)
	FIELD(unk0x67)
	FIELD(dwSpeed)
	FIELD(unk0x69)
	OBJECT(tDirectionVector)
	OBJECT(tVelocityVector)
	ARRAY(padding0x7A)
	FIELD(dwVelocity)
	FIELD(nPreviousVelocity)
	FIELD(dwMaxVelocity)
	FIELD(dwAcceleration)
	FIELD(dwAccelerationsCounter)
	FIELD(nDist)
	FIELD(nDistMax)
	FIELD(nIDAStarInitFScore)
	FIELD(nStepNum)
	FIELD(nDistance)
	ARRAY(padding0x95)
	FIELD(nDirOffset)
	ARRAY(PathPoints)
	FIELD(nSavedStepsCount)
	ARRAY(SavedSteps)
END_VISIT()

BEGIN_VISIT(D2PathInfoStrc)
	//OBJECT(tStartCoord)
	//OBJECT(tTargetCoord)
	//POINTER(pStartRoom)
	//POINTER(pTargetRoom)
	//FIELD(field_10)
	//FIELD(field_14)
	//FIELD(field_15)
	//FIELD(field_16)
	//FIELD(nDistMax)
	//FIELD(nMinimumFScoreToEvaluate)
	//FIELD(field_1D)
	//FIELD(field_1E)
	//FIELD(nPathType)
	//FIELD(nUnitSize)
	//FIELD(nCollisionPattern)
	//FIELD(nCollisionMask)
	//BEGIN_UNION()
		//POINTER(pDynamicPath)
		//POINTER(pNext)
	//END_UNION()
END_VISIT()

BEGIN_VISIT(D2StaticPathStrc)
	//POINTER(pRoom)
	//FIELD(dwClientCoordX)
	//FIELD(dwClientCoordY)
	//OBJECT(tGameCoords)
	//ARRAY(unk0x14)
	//FIELD(nDirection)
	//FIELD(bRoomNeedsUpdate)
	//ARRAY(unk0x1E)
END_VISIT()

BEGIN_VISIT(D2MapAIPathPositionStrc)
	//FIELD(nMapAIAction)
	//FIELD(nX)
	//FIELD(nY)
END_VISIT()

BEGIN_VISIT(D2MapAIStrc)
	//FIELD(nPathNodes)
	//POINTER(pPosition)
END_VISIT()
