#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <Units/Missile.h>


BEGIN_VISIT(D2UnkMissileCalcStrc)
	//FIELD(field_0)
	//FIELD(field_4)
	//FIELD(field_8)
	//FIELD(field_C)
	//FIELD(field_10)
	//FIELD(field_14)
	//FIELD(field_18)
	//FIELD(field_1C)
	//OBJECT(pSeed)
END_VISIT()

BEGIN_VISIT(D2MissileCalcStrc)
	//POINTER(pMissile)
	//POINTER(pOwner)
	//FIELD(nMissileId)
	//FIELD(nMissileLevel)
END_VISIT()

BEGIN_VISIT(D2MissileDamageDataStrc)
	//FIELD(nFlags)
	//FIELD(nMinDamage)
	//FIELD(nMaxDamage)
	//FIELD(nFireMinDamage)
	//FIELD(nFireMaxDamage)
	//FIELD(nFireLength)
	//FIELD(nLightMinDamage)
	//FIELD(nLightMaxDamage)
	//FIELD(nMagicMinDamage)
	//FIELD(nMagicMaxDamage)
	//FIELD(nColdMinDamage)
	//FIELD(nColdMaxDamage)
	//FIELD(nColdLength)
	//FIELD(nPoisonMinDamage)
	//FIELD(nPoisonMaxDamage)
	//FIELD(nPoisonLength)
	//FIELD(nPoisonCount)
	//FIELD(nLifeDrainMinDamage)
	//FIELD(nLifeDrainMaxDamage)
	//FIELD(nManaDrainMinDamage)
	//FIELD(nManaDrainMaxDamage)
	//FIELD(nStaminaDrainMinDamage)
	//FIELD(nStaminaDrainMaxDamage)
	//FIELD(nStunLength)
	//FIELD(nBurningMin)
	//FIELD(nBurningMax)
	//FIELD(nBurnLength)
	//FIELD(nDemonDamagePercent)
	//FIELD(nUndeadDamagePercent)
	//FIELD(nDamageTargetAC)
	//FIELD(nDamagePercent)
END_VISIT()

BEGIN_VISIT(D2MissileDataStrc)
	FIELD(unk0x00)
	FIELD(nStreamMissile)
	FIELD(nStreamRange)
	FIELD(nActivateFrame)
	FIELD(nSkill)
	FIELD(nLevel)
	FIELD(nTotalFrames)
	FIELD(nCurrentFrame)
	FIELD(unk0x12)
	FIELD(fFlags)
	FIELD(nOwnerType)
	FIELD(dwOwnerGUID)
	FIELD(nHomeType)
	FIELD(dwHomeGUID)
	//BEGIN_UNION()
		//FIELD(nStatus)
		//OBJECT(pCoords)
		//OBJECT(pTargetCoords)
	//END_UNION()
	//POINTER(pStream)
END_VISIT()

BEGIN_VISIT(D2MissileStrc)
	FIELD(dwFlags)
	POINTER(pOwner)
	POINTER(pOrigin)
	POINTER(pTarget)
	FIELD(nMissile)
	FIELD(nX)
	FIELD(nY)
	FIELD(nTargetX)
	FIELD(nTargetY)
	FIELD(nGfxArg)
	FIELD(nVelocity)
	FIELD(nSkill)
	FIELD(nSkillLevel)
	FIELD(nLoops)
	FIELD(unk0x38)
	FIELD(unk0x3C)
	FIELD(nFrame)
	FIELD(nActivateFrame)
	FIELD(nAttBonus)
	FIELD(nRange)
	FIELD(nLightRadius)
	//OBJECT(pInitFunc)
	//FIELD(pInitArgs)
END_VISIT()
