#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <Units/Player.h>


BEGIN_VISIT(D2PlayerCountBonusStrc)
	//FIELD(nHp)
	//FIELD(nExperience)
	//FIELD(nMonsterSkillBonus)
	//FIELD(nDifficulty)
	//FIELD(nPlayerCount)
END_VISIT()

BEGIN_VISIT(D2ItemTradeStrc)
	//FIELD(nItemGUID1)
	//FIELD(nItemGUID2)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2PlayerTradeStrc)
	//FIELD(nSaveLength)
	//POINTER(pSaveData)
	//POINTER(pItemTrade)
	//FIELD(nGoldInTrade)
	//FIELD(nGoldInTradeOtherPlayer)
	//FIELD(nNextUpdateTick)
END_VISIT()

BEGIN_VISIT(D2PlrIntroStrc)
	//POINTER(pQuestIntroFlags)
	//POINTER(pNpcIntroFlags)
END_VISIT()

BEGIN_VISIT(D2PetInfoStrc)
	//FIELD(nSeed)
	//FIELD(wName)
	//FIELD(unk0x06)
	//FIELD(nHirelingId)
END_VISIT()

BEGIN_VISIT(D2PetDataStrc)
	//FIELD(nFlags)
	//FIELD(nUnitGUID)
	//OBJECT(petInfo)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2PetListStrc)
	//POINTER(pPetData)
	//FIELD(nCurrent)
	//FIELD(nMax)
END_VISIT()

BEGIN_VISIT(D2PlayerPetStrc)
	//POINTER(pPetList)
END_VISIT()

BEGIN_VISIT(D2PetArgStrc)
	//FIELD(nPetGUID)
	//FIELD(nUnitGUID)
	//FIELD(nPetClass)
	//FIELD(unk0x0A)
	//FIELD(nPetType)
	//FIELD(nSeed)
	//FIELD(wName)
	//FIELD(unk0x16)
	//FIELD(unk0x18)
END_VISIT()

BEGIN_VISIT(D2PlayerListStrc)
	//FIELD(nUnitGUID)
	//FIELD(dwFlags)
	//FIELD(field_8)
	//FIELD(field_C)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2UnkPlayerDataStrc)
	//FIELD(nUnitGUID)
	//FIELD(unk0x04)
	//FIELD(unk0x08)
	//FIELD(unk0x0C)
	//ARRAY(unk0x0D)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2PlayerDataStrc)
	//ARRAY(szName)
	//ARRAY(pQuestData)
	//ARRAY(pWaypointData)
	//FIELD(unk0x28)
	//FIELD(nPortalFlags)
	//FIELD(unk0x30)
	//POINTER(pArenaUnit)
	//POINTER(pPlayerList)
	//ARRAY(unk0x3C)
	//POINTER(pPlayerPets)
	//FIELD(dwUniqueId)
	//FIELD(bBusy)
	//FIELD(dwTradeState)
	//FIELD(unk0x54)
	//FIELD(dwAcceptTradeTick)
	//POINTER(pTrade)
	//ARRAY(pPlayerIntro)
	//FIELD(dwBoughtItemId)
	//FIELD(nRightSkillId)
	//FIELD(nLeftSkillId)
	//FIELD(nRightSkillFlags)
	//FIELD(nLeftSkillFlags)
	//FIELD(nSwitchRightSkillId)
	//FIELD(nSwitchLeftSkillId)
	//FIELD(nSwitchRightSkillFlags)
	//FIELD(nSwitchLeftSkillFlags)
	//FIELD(nWeaponGUID)
	//FIELD(unk0x94)
	//POINTER(unk0x98)
	//POINTER(pClient)
	//FIELD(unk0xA0)
	//ARRAY(unk0xA1)
	//FIELD(unk0xA4)
	//ARRAY(unk0xA8)
	//FIELD(dwHostileDelay)
	//FIELD(unk0x164)
	//FIELD(dwGameFrame)
END_VISIT()
