#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <Units/Units.h>


BEGIN_VISIT(D2UnitPacketListStrc)
	//POINTER(pNext)
	//FIELD(nHeader)
END_VISIT()

BEGIN_VISIT(D2UnitStrc)
	//FIELD(dwUnitType)
	//FIELD(dwClassId)
	//OMIT(pMemoryPool)
	//FIELD(dwUnitId)
	//BEGIN_UNION()
		//FIELD(dwAnimMode)
		//FIELD(dwItemMode)
		//FIELD(dwMissileMode)
	//END_UNION()
	//BEGIN_UNION()
		//POINTER(pPlayerData)
		//POINTER(pItemData)
		//POINTER(pMonsterData)
		//POINTER(pObjectData)
		//POINTER(pMissileData)
	//END_UNION()
	//FIELD(nAct)
	//ARRAY(unk0x19)
	//POINTER(pDrlgAct)
	//OBJECT(pSeed)
	//FIELD(dwInitSeed)
	//BEGIN_UNION()
		//POINTER(pDynamicPath)
		//POINTER(pStaticPath)
	//END_UNION()
	//POINTER(pAnimSeq)
	//FIELD(dwSeqFrameCount)
	//FIELD(dwSeqFrame)
	//FIELD(dwSeqSpeed)
	//FIELD(dwSeqMode)
	//FIELD(nSeqCurrentFramePrecise)
	//FIELD(dwFrameCountPrecise)
	//FIELD(wAnimSpeed)
	//FIELD(nActionFrame)
	//FIELD(unk0x4F)
	//POINTER(pAnimData)
	//POINTER(pGfxData)
	//POINTER(pGfxDataCopy)
	//POINTER(pStatListEx)
	//POINTER(pInventory)
	//BEGIN_UNION()
		//OBJECT(dwInteractGUID)
		//FIELD(dwInteractType)
		//FIELD(nInteract)
		//FIELD(nUpdateType)
		//POINTER(pUpdateUnit)
		//POINTER(pQuestEventList)
		//FIELD(bSparkChest)
		//OMIT(pTimerParams)
		//POINTER(pGame)
		//ARRAY(unk0x084)
		//POINTER(pSrvUnitEventsList)
		//POINTER(pLight)
		//FIELD(dwStartLight)
		//FIELD(nPaletteIndex)
		//FIELD(bUnitSfx)
		//FIELD(dwSfxMode)
		//OMIT(pUnitSfxData)
		//FIELD(dwSfxTicks)
		//FIELD(dwSfxAsyncTicks)
		//FIELD(dwSfxStepTicks)
		//FIELD(bHasActiveSound)
		//FIELD(nLastClickX)
		//FIELD(nLastClickY)
		//POINTER(pCltTimerList)
	//END_UNION()
	//FIELD(dwOwnerType)
	//FIELD(dwOwnerGUID)
	//FIELD(dwKillerType)
	//FIELD(dwKillerGUID)
	//POINTER(pHoverText)
	//POINTER(pSkills)
	//POINTER(pCombat)
	//FIELD(dwLastHitClass)
	//FIELD(unk0xB4)
	//FIELD(dwDropItemCode)
	//ARRAY(unk0xBC)
	//FIELD(dwFlags)
	//FIELD(dwFlagEx)
	//OMIT(pUnused0xCC)
	//FIELD(dwNodeIndex)
	//FIELD(dwTickCount)
	//BEGIN_UNION()
		//FIELD(dwSrvTickCount)
		//POINTER(pPacketList)
	//END_UNION()
	//POINTER(pTimer)
	//POINTER(pChangeNextUnit)
	//POINTER(pListNext)
	//POINTER(pRoomNext)
	//POINTER(pMsgFirst)
	//POINTER(pMsgLast)
END_VISIT()
