#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <GAME/Clients.h>


BEGIN_VISIT(D2ClientInfoStrc)
	//POINTER(pSelf)
	//FIELD(dwClientId)
	//FIELD(nFlags)
	//POINTER(szKickMessage)
	//FIELD(unk0x10)
	//FIELD(dwLastPacketResetTick)
	//FIELD(nPacketsPerSecond)
	//FIELD(dwNewGameTick)
	//FIELD(dwRemoveTick)
	//FIELD(unk0x24)
	//FIELD(unk0x28)
	//FIELD(dwHackDetectionPacketTick)
	//FIELD(nACDataCount)
	//FIELD(unk0x34)
	//FIELD(unk0x38)
	//FIELD(unk0x3C)
END_VISIT()

BEGIN_VISIT(D2ClientPlayerDataStrc)
	//FIELD(dwInactivityTime)
	//FIELD(nHitPoints)
	//FIELD(nManaPoints)
	//FIELD(nStaminaPoints)
	//FIELD(nPotionLifePercent)
	//FIELD(nPotionManaPercent)
	//FIELD(nPosX)
	//FIELD(nPosY)
	//FIELD(nTargetOffsetX)
	//FIELD(nTargetOffsetY)
	//FIELD(dwBeltGold)
	//FIELD(dwExperience)
END_VISIT()

BEGIN_VISIT(D2ClientUnitUpdateSortStrc)
	//POINTER(pUnit)
	//FIELD(nDistance)
	//FIELD(nNextIndex)
END_VISIT()

BEGIN_VISIT(D2ClientKeySkillStrc)
	//FIELD(nSkill)
	//FIELD(nHand)
	//FIELD(nItemGUID)
END_VISIT()

BEGIN_VISIT(D2GuildInformationStrc)
	//FIELD(nGuildFlags)
	//FIELD(szGuildTag)
	//ARRAY(szGuildName)
	//FIELD(nBackgroundColor)
	//FIELD(nForegroundColor)
	//FIELD(nEmblemType)
END_VISIT()

BEGIN_VISIT(D2ClientStrc)
	//FIELD(dwClientId)
	//OBJECT(dwClientState)
	//FIELD(nClassId)
	//FIELD(unk0x09)
	//OBJECT(tSaveFlags)
	//FIELD(nCharTemplate)
	//ARRAY(szName)
	//ARRAY(szAccount)
	//ARRAY(unk0x2D)
	//FIELD(nCharSaveTransactionToken)
	//FIELD(unk0x64)
	//POINTER(pClientInfo)
	//OBJECT(tCharacterInfo)
	//ARRAY(unk0x92)
	//FIELD(dwUnitType)
	//FIELD(dwUnitGUID)
	//POINTER(pPlayer)
	//FIELD(bUnlockCharacter)
	//POINTER(pSaveHeader)
	//FIELD(nSaveHeaderSize)
	//FIELD(unk0x184)
	//FIELD(nSaveHeaderDataSentBytes)
	//FIELD(nSaveChecksum)
	//OBJECT(nSaveCreationTimestamp)
	//ARRAY(unk0x198)
	//POINTER(pGame)
	//FIELD(nAct)
	//ARRAY(pad0x1AD)
	//FIELD(unk0x1B0)
	//POINTER(pRoom)
	//OBJECT(tPacketDataList)
	//FIELD(nSaveHeaderSendFailures)
	//FIELD(unk0x1C8)
	//ARRAY(unitUpdate)
	//FIELD(pad0x3BB)
	//FIELD(nUnitUpdateIndex)
	//ARRAY(aLastWarpAttemptsFrame)
	//FIELD(dwFlags)
	//FIELD(dwLastPacketTick)
	//ARRAY(HotkeySkills)
	//FIELD(bSwitchWeapon)
	//FIELD(padding0x45D)
	//OBJECT(tGuildInfo)
	//FIELD(padding0x483)
	//FIELD(nIronGolemItemGUID)
	//FIELD(nCreateTime)
	//OBJECT(clientPlayerData)
	//POINTER(pNext)
	//POINTER(pServerNext)
	//POINTER(pServerNextByName)
	//ARRAY(aPingHistory)
	//FIELD(nPingMovingAverage)
	//FIELD(dwPingsCount)
#ifdef D2_VERSION_113C
	//FIELD(unk0x504)
#endif
	//FIELD(nExpLoss)
	//FIELD(dwLocale)
	//FIELD(dwLangId)
#ifdef D2_VERSION_113C
	//FIELD(pad0x514)
#endif
END_VISIT()
