#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <DataTbls/LevelsTbls.h>


BEGIN_VISIT(D2AutomapTxt)
	//ARRAY(szLevelName)
	//ARRAY(szTileName)
	//FIELD(nStyle)
	//FIELD(nStartSequence)
	//FIELD(nEndSequence)
	//FIELD(pad0x1B)
	//ARRAY(nCel)
END_VISIT()

BEGIN_VISIT(D2AutomapRandStrc)
	//FIELD(nStart)
	//FIELD(nEnd)
END_VISIT()

BEGIN_VISIT(D2AutomapShortStrc)
	//FIELD(dwAutomapLevelType)
	//FIELD(dwAutomapTileType)
	//FIELD(nStyle)
	//FIELD(nStartSequence)
	//FIELD(nEndSequence)
	//FIELD(pad0x0B)
	//ARRAY(nCel)
	//FIELD(nCels)
END_VISIT()

BEGIN_VISIT(D2LevelDefBin)
	//FIELD(dwQuestFlag)
	//FIELD(dwQuestFlagEx)
	//FIELD(dwLayer)
	//ARRAY(dwSizeX)
	//ARRAY(dwSizeY)
	//FIELD(dwOffsetX)
	//FIELD(dwOffsetY)
	//FIELD(dwDepend)
	//FIELD(dwDrlgType)
	//FIELD(dwLevelType)
	//FIELD(dwSubType)
	//FIELD(dwSubTheme)
	//FIELD(dwSubWaypoint)
	//FIELD(dwSubShrine)
	//ARRAY(dwVis)
	//ARRAY(dwWarp)
	//FIELD(nIntensity)
	//FIELD(nRed)
	//FIELD(nGreen)
	//FIELD(nBlue)
	//FIELD(dwPortal)
	//FIELD(dwPosition)
	//FIELD(dwSaveMonsters)
	//FIELD(dwLOSDraw)
END_VISIT()

BEGIN_VISIT(D2LevelsTxt)
	//FIELD(wLevelNo)
	//FIELD(nPal)
	//FIELD(nAct)
	//FIELD(nTeleport)
	//FIELD(nRain)
	//FIELD(nMud)
	//FIELD(nNoPer)
	//FIELD(nIsInside)
	//FIELD(nDrawEdges)
	//FIELD(unk0x0A)
	//FIELD(dwWarpDist)
	//ARRAY(wMonLvl)
	//ARRAY(wMonLvlEx)
	//ARRAY(dwMonDen)
	//ARRAY(nMonUMin)
	//ARRAY(nMonUMax)
	//FIELD(nMonWndr)
	//FIELD(nMonSpcWalk)
	//FIELD(nQuest)
	//FIELD(nRangedSpawn)
	//FIELD(nNumMon)
	//FIELD(nNumNormalMonsters)
	//FIELD(nNumNightmareHellMonsters)
	//FIELD(nNumUniqueMonsters)
	//ARRAY(wNormalMonsters)
	//ARRAY(wNightmareHellMonsters)
	//ARRAY(wUniqueMonsters)
	//ARRAY(wCMon)
	//ARRAY(wCPct)
	//ARRAY(wCAmt)
	//FIELD(nWaypoint)
	//ARRAY(nObjGroup)
	//ARRAY(nObjPrb)
	//ARRAY(szLevelName)
	//ARRAY(szLevelWarp)
	//ARRAY(szEntryFile)
	//FIELD(pad0x16D)
	//ARRAY(wszLevelName)
	//ARRAY(wszLevelWarp)
	//FIELD(pad0x20E)
	//FIELD(dwThemes)
	//FIELD(dwFloorFilter)
	//FIELD(dwBlankScreen)
	//FIELD(dwSoundEnv)
END_VISIT()

BEGIN_VISIT(D2LvlMazeTxt)
	//FIELD(dwLevelId)
	//ARRAY(dwRooms)
	//FIELD(dwSizeX)
	//FIELD(dwSizeY)
	//FIELD(dwMerge)
END_VISIT()

BEGIN_VISIT(D2LvlPrestTxt)
	//FIELD(dwDef)
	//FIELD(dwLevelId)
	//FIELD(dwPopulate)
	//FIELD(dwLogicals)
	//FIELD(dwOutdoors)
	//FIELD(dwAnimate)
	//FIELD(dwKillEdge)
	//FIELD(dwFillBlanks)
	//FIELD(dwExpansion)
	//FIELD(nAnimSpeed)
	//FIELD(nSizeX)
	//FIELD(nSizeY)
	//FIELD(dwAutoMap)
	//FIELD(dwScan)
	//FIELD(dwPops)
	//FIELD(dwPopPad)
	//FIELD(dwFiles)
	//ARRAY(szFile)
	//FIELD(dwDt1Mask)
END_VISIT()

BEGIN_VISIT(D2LvlSubTxt)
	//FIELD(dwType)
	//ARRAY(szFile)
	//FIELD(dwCheckAll)
	//FIELD(dwBordType)
	//FIELD(dwDt1Mask)
	//FIELD(dwGridSize)
	//POINTER(pDrlgFile)
	//ARRAY(pTileTypeGrid)
	//ARRAY(pWallGrid)
	//OBJECT(pFloorGrid)
	//OBJECT(pShadowGrid)
	//ARRAY(nProb)
	//ARRAY(nTrials)
	//ARRAY(nMax)
	//FIELD(dwExpansion)
END_VISIT()

BEGIN_VISIT(D2LvlTypesTxt)
	//ARRAY(szFile)
	//FIELD(nAct)
	//ARRAY(pad0x781)
	//FIELD(dwExpansion)
END_VISIT()

BEGIN_VISIT(D2LvlWarpTxt)
	//FIELD(dwLevelId)
	//FIELD(dwSelectX)
	//FIELD(dwSelectY)
	//FIELD(dwSelectDX)
	//FIELD(dwSelectDY)
	//FIELD(dwExitWalkX)
	//FIELD(dwExitWalkY)
	//FIELD(dwOffsetX)
	//FIELD(dwOffsetY)
	//FIELD(dwLitVersion)
	//FIELD(dwTiles)
	//ARRAY(szDirection)
END_VISIT()
