#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <DataTbls/MissilesTbls.h>


BEGIN_VISIT(D2MissilesTxt)
	//FIELD(wId)
	//FIELD(pad0x02)
	//FIELD(dwMissileFlags)
	//FIELD(wCltDoFunc)
	//FIELD(wCltHitFunc)
	//FIELD(wSrvDoFunc)
	//FIELD(wSrvHitFunc)
	//FIELD(wSrvDmgFunc)
	//FIELD(wTravelSound)
	//FIELD(wHitSound)
	//FIELD(wExplosionMissile)
	//ARRAY(wSubMissile)
	//ARRAY(wCltSubMissile)
	//ARRAY(wHitSubMissile)
	//ARRAY(wCltHitSubMissile)
	//FIELD(wProgSound)
	//FIELD(wProgOverlay)
	//ARRAY(dwParam)
	//ARRAY(dwHitPar)
	//ARRAY(dwCltParam)
	//ARRAY(dwCltHitPar)
	//ARRAY(dwDmgParam)
	//FIELD(dwSrvCalc)
	//FIELD(dwCltCalc)
	//FIELD(dwHitCalc)
	//FIELD(dwCltHitCalc)
	//FIELD(dwDmgCalc)
	//FIELD(nHitClass)
	//FIELD(pad0x95)
	//FIELD(wRange)
	//FIELD(wLevRange)
	//FIELD(nVel)
	//FIELD(nVelLev)
	//FIELD(nMaxVel)
	//FIELD(pad0x9D)
	//FIELD(wAccel)
	//FIELD(wAnimRate)
	//FIELD(wXoffset)
	//FIELD(wYoffset)
	//FIELD(wZoffset)
	//FIELD(dwHitFlags)
	//FIELD(wResultFlags)
	//FIELD(nKnockBack)
	//FIELD(pad0xAF)
	//FIELD(dwMinDamage)
	//FIELD(dwMaxDamage)
	//ARRAY(dwMinLevDam)
	//ARRAY(dwMaxLevDam)
	//FIELD(dwDmgSymPerCalc)
	//FIELD(nElemType)
	//ARRAY(pad0xE5)
	//FIELD(dwElemMin)
	//FIELD(dwElemMax)
	//ARRAY(dwMinElemLev)
	//ARRAY(dwMaxElemLev)
	//FIELD(dwElemDmgSymPerCalc)
	//FIELD(dwElemLen)
	//ARRAY(dwElemLevLen)
	//FIELD(nCltSrcTown)
	//FIELD(nSrcDamage)
	//FIELD(nSrcMissDmg)
	//FIELD(nHoly)
	//FIELD(nLight)
	//FIELD(nFlicker)
	//ARRAY(nRGB)
	//FIELD(nInitSteps)
	//FIELD(nActivate)
	//FIELD(nLoopAnim)
	//ARRAY(szCelFile)
	//FIELD(nAnimLen)
	//ARRAY(pad0x179)
	//FIELD(dwRandStart)
	//FIELD(nSubLoop)
	//FIELD(nSubStart)
	//FIELD(nSubStop)
	//FIELD(nCollideType)
	//FIELD(nCollision)
	//FIELD(nClientCol)
	//FIELD(nCollideKill)
	//FIELD(nCollideFriend)
	//FIELD(nNextHit)
	//FIELD(nNextDelay)
	//FIELD(nSize)
	//FIELD(nToHit)
	//FIELD(nAlwaysExplode)
	//FIELD(nTrans)
	//FIELD(nQty)
	//FIELD(pad0x18F)
	//FIELD(dwSpecialSetup)
	//FIELD(nSkill)
	//FIELD(nHitShift)
	//ARRAY(unk0x197)
	//FIELD(dwDamageRate)
	//FIELD(nNumDirections)
	//FIELD(nAnimSpeed)
	//FIELD(nLocalBlood)
	//FIELD(pad0x1A3)
END_VISIT()
