#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <DataTbls/ObjectsTbls.h>


BEGIN_VISIT(D2ObjectsTxt)
	//ARRAY(szName)
	//ARRAY(wszName)
	//ARRAY(szToken)
	//FIELD(nSpawnMax)
	//ARRAY(nSelectable)
	//FIELD(nTrapProb)
	//ARRAY(pad0xCD)
	//FIELD(dwSizeX)
	//FIELD(dwSizeY)
	//ARRAY(dwFrameCnt)
	//ARRAY(wFrameDelta)
	//ARRAY(nCycleAnim)
	//ARRAY(nLit)
	//ARRAY(nBlocksLight)
	//ARRAY(nHasCollision)
	//FIELD(nIsAttackable0)
	//ARRAY(nStart)
	//ARRAY(nOrderFlag)
	//FIELD(nEnvEffect)
	//FIELD(nIsDoor)
	//FIELD(nBlocksVis)
	//FIELD(nOrientation)
	//FIELD(nPreOperate)
	//FIELD(nTrans)
	//ARRAY(nMode)
	//FIELD(pad0x147)
	//FIELD(dwXOffset)
	//FIELD(dwYOffset)
	//FIELD(nDraw)
	//FIELD(nHD)
	//FIELD(nTR)
	//FIELD(nLG)
	//FIELD(nRA)
	//FIELD(nLA)
	//FIELD(nRH)
	//FIELD(nLH)
	//FIELD(nSH)
	//FIELD(nS1)
	//FIELD(nS2)
	//FIELD(nS3)
	//FIELD(nS4)
	//FIELD(nS5)
	//FIELD(nS6)
	//FIELD(nS7)
	//FIELD(nS8)
	//FIELD(nTotalPieces)
	//FIELD(nXSpace)
	//FIELD(nYSpace)
	//FIELD(nRed)
	//FIELD(nGreen)
	//FIELD(nBlue)
	//FIELD(nSubClass)
	//FIELD(dwNameOffset)
	//FIELD(pad0x16C)
	//FIELD(nMonsterOK)
	//FIELD(nOperateRange)
	//FIELD(nShrineFunction)
	//FIELD(nAct)
	//FIELD(nLockable)
	//FIELD(nGore)
	//FIELD(nRestore)
	//FIELD(nRestoreVirgins)
	//FIELD(nSync)
	//FIELD(pad0x176)
	//ARRAY(dwParm)
	//FIELD(nTgtFX)
	//FIELD(nTgtFY)
	//FIELD(nTgtBX)
	//FIELD(nTgtBY)
	//FIELD(nDamage)
	//FIELD(nCollisionSubst)
	//FIELD(pad0x19E)
	//FIELD(dwLeft)
	//FIELD(dwTop)
	//FIELD(dwWidth)
	//FIELD(dwHeight)
	//FIELD(nBeta)
	//FIELD(nInitFn)
	//FIELD(nPopulateFn)
	//FIELD(nOperateFn)
	//FIELD(nClientFn)
	//FIELD(nOverlay)
	//FIELD(nBlockMissile)
	//FIELD(nDrawUnder)
	//FIELD(nOpenWarp)
	//ARRAY(pad0x1B9)
	//FIELD(dwAutomap)
END_VISIT()

BEGIN_VISIT(D2ObjGroupTxt)
	//ARRAY(dwId)
	//ARRAY(nDensity)
	//ARRAY(nProbability)
	//FIELD(nShrines)
	//FIELD(nWells)
	//FIELD(pad0x32)
END_VISIT()

BEGIN_VISIT(D2ShrinesTxt)
	//FIELD(nCode)
	//ARRAY(pad0x01)
	//FIELD(dwArg0)
	//FIELD(dwArg1)
	//FIELD(dwDurationInFrames)
	//FIELD(nResetTimeInMins)
	//FIELD(nRarity)
	//ARRAY(szViewname)
	//ARRAY(szNiftyphrase)
	//FIELD(nEffectClass)
	//FIELD(pad0xB3)
	//FIELD(dwLevelMin)
END_VISIT()
