add_library(TestDefinitions STATIC src/TestDefinitions.cpp)

target_sources(TestDefinitions
  PRIVATE
    include/TestDefinitions.h
    include/EqualityMacros.h
    
    include/D2Common/DataTbls/AnimTblsVisitorDefinitions.h
    include/D2Common/DataTbls/ArenaTblsVisitorDefinitions.h
    include/D2Common/DataTbls/BeltsTblsVisitorDefinitions.h
    include/D2Common/DataTbls/FieldTblsVisitorDefinitions.h
    include/D2Common/DataTbls/HoradricCubeVisitorDefinitions.h
    include/D2Common/DataTbls/InvTblsVisitorDefinitions.h
    include/D2Common/DataTbls/ItemsTblsVisitorDefinitions.h
    include/D2Common/DataTbls/LevelsTblsVisitorDefinitions.h
    include/D2Common/DataTbls/MissilesTblsVisitorDefinitions.h
    include/D2Common/DataTbls/MonsterTblsVisitorDefinitions.h
    include/D2Common/DataTbls/ObjectsTblsVisitorDefinitions.h
    include/D2Common/DataTbls/OverlayTblsVisitorDefinitions.h
    include/D2Common/DataTbls/SequenceTblsVisitorDefinitions.h
    include/D2Common/DataTbls/SkillsTblsVisitorDefinitions.h
    include/D2Common/DataTbls/TokenTblsVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgDrlgVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgDrlgGridVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgDrlgLogicVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgDrlgVerVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgMazeVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgOutdoorsVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgOutPlaceVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgOutRoomVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgPresetVisitorDefinitions.h
    include/D2Common/Drlg/D2DrlgTileSubVisitorDefinitions.h
    include/D2Common/Path/AStarVisitorDefinitions.h
    include/D2Common/Path/IDAStarVisitorDefinitions.h
    include/D2Common/Path/PathVisitorDefinitions.h
    include/D2Common/Units/ItemVisitorDefinitions.h
    include/D2Common/Units/MissileVisitorDefinitions.h
    include/D2Common/Units/MissileStreamVisitorDefinitions.h
    include/D2Common/Units/MonsterVisitorDefinitions.h
    include/D2Common/Units/ObjectVisitorDefinitions.h
    include/D2Common/Units/PlayerVisitorDefinitions.h
    include/D2Common/Units/UnitFindsVisitorDefinitions.h
    include/D2Common/Units/UnitsVisitorDefinitions.h
    include/D2Common/D2ChatVisitorDefinitions.h
    include/D2Common/D2CollisionVisitorDefinitions.h
    include/D2Common/D2CompositVisitorDefinitions.h
    include/D2Common/D2DataTblsVisitorDefinitions.h
    include/D2Common/D2EnvironmentVisitorDefinitions.h
    include/D2Common/D2InventoryVisitorDefinitions.h
    include/D2Common/D2ItemModsVisitorDefinitions.h
    include/D2Common/D2ItemsVisitorDefinitions.h
    include/D2Common/D2MonstersVisitorDefinitions.h
    include/D2Common/D2SeedVisitorDefinitions.h
    include/D2Common/D2SkillsVisitorDefinitions.h
    include/D2Common/D2StatListVisitorDefinitions.h
    include/D2Common/D2TextVisitorDefinitions.h
    include/D2Common/D2WaypointsVisitorDefinitions.h
    
    include/D2Game/AI/AiGeneralVisitorDefinitions.h
    include/D2Game/AI/AiTacticsVisitorDefinitions.h
    include/D2Game/AI/AiUtilVisitorDefinitions.h
    include/D2Game/GAME/ArenaVisitorDefinitions.h
    include/D2Game/GAME/ClientsVisitorDefinitions.h
    include/D2Game/GAME/EventVisitorDefinitions.h
    include/D2Game/GAME/GameVisitorDefinitions.h
    include/D2Game/GAME/TaskVisitorDefinitions.h
    include/D2Game/ITEMS/ItemModeVisitorDefinitions.h
    include/D2Game/ITEMS/ItemsVisitorDefinitions.h
    include/D2Game/MISSILES/MissModeVisitorDefinitions.h
    include/D2Game/MONSTER/MonsterAIVisitorDefinitions.h
    include/D2Game/MONSTER/MonsterModeVisitorDefinitions.h
    include/D2Game/MONSTER/MonsterRegionVisitorDefinitions.h
    include/D2Game/MONSTER/MonsterSpawnVisitorDefinitions.h
    include/D2Game/OBJECTS/ObjectsVisitorDefinitions.h
    include/D2Game/OBJECTS/ObjModeVisitorDefinitions.h
    include/D2Game/PLAYER/PlrModesVisitorDefinitions.h
    include/D2Game/PLAYER/PlrSaveVisitorDefinitions.h
    include/D2Game/PLAYER/PlrSave2VisitorDefinitions.h
    include/D2Game/PLAYER/PlrTradeVisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q1VisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q2VisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q3VisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q4VisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q5VisitorDefinitions.h
    include/D2Game/QUESTS/ACT1/A1Q6VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q0VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q1VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q2VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q3VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q4VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q5VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q6VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q7VisitorDefinitions.h
    include/D2Game/QUESTS/ACT2/A2Q8VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q0VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q1VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q2VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q3VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q4VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q5VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q6VisitorDefinitions.h
    include/D2Game/QUESTS/ACT3/A3Q7VisitorDefinitions.h
    include/D2Game/QUESTS/ACT4/A4Q1VisitorDefinitions.h
    include/D2Game/QUESTS/ACT4/A4Q2VisitorDefinitions.h
    include/D2Game/QUESTS/ACT4/A4Q3VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q1VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q2VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q3VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q4VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q5VisitorDefinitions.h
    include/D2Game/QUESTS/ACT5/A5Q6VisitorDefinitions.h
    include/D2Game/QUESTS/QuestsVisitorDefinitions.h
    include/D2Game/SKILLS/SkillItemVisitorDefinitions.h
    include/D2Game/SKILLS/SkillsVisitorDefinitions.h
    include/D2Game/UNIT/PartyVisitorDefinitions.h
    include/D2Game/UNIT/SUnitVisitorDefinitions.h
    include/D2Game/UNIT/SUnitDmgVisitorDefinitions.h
    include/D2Game/UNIT/SUnitEventVisitorDefinitions.h
    include/D2Game/UNIT/SUnitInactiveVisitorDefinitions.h
    include/D2Game/UNIT/SUnitNpcVisitorDefinitions.h
    include/D2Game/UNIT/SUnitProxyVisitorDefinitions.h
    include/D2Game/D2PacketVisitorDefinitions.h
)
target_include_directories(TestDefinitions PUBLIC include)
target_link_libraries(TestDefinitions PRIVATE D2CommonDefinitions D2Common VisitorFramework)
target_compile_features(TestDefinitions PRIVATE cxx_std_17)

get_target_property(TestDefinitionsSources TestDefinitions SOURCES)
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${TestDefinitionsSources})
