#pragma once


#include <DiffContext.h>
#include <DiffVisitor.h>
#include <Macros.h>
#include <TypeId.h>
#include <TypeRegistration.h>


#include <Drlg/D2DrlgDrlg.h>


BEGIN_VISIT(D2DrlgCoordsStrc)
	//FIELD(nSubtileX)
	//FIELD(nSubtileY)
	//FIELD(nSubtileWidth)
	//FIELD(nSubtileHeight)
	//FIELD(nTileXPos)
	//FIELD(nTileYPos)
	//FIELD(nTileWidth)
	//FIELD(nTileHeight)
END_VISIT()

BEGIN_VISIT(D2DrlgRoomStrc)
	//POINTER(pLevel)
	//BEGIN_UNION()
		//FIELD(nTileXPos)
		//FIELD(nTileYPos)
		//FIELD(nTileWidth)
		//FIELD(nTileHeight)
		//OBJECT(pDrlgCoord)
	//END_UNION()
	//FIELD(dwFlags)
	//FIELD(dwOtherFlags)
	//FIELD(nType)
	//BEGIN_UNION()
		//POINTER(pMaze)
		//POINTER(pOutdoor)
	//END_UNION()
	//FIELD(dwDT1Mask)
	//ARRAY(pTiles)
	//POINTER(pTileGrid)
	//FIELD(fRoomStatus)
	//FIELD(unk0xAD)
	//ARRAY(wRoomsInList)
	//POINTER(pStatusNext)
	//POINTER(pStatusPrev)
	//POINTER(ppRoomsNear)
	//FIELD(nRoomsNear)
	//POINTER(pRoomTiles)
	//POINTER(pPresetUnits)
	//POINTER(pDrlgOrth)
	//OBJECT(pSeed)
	//FIELD(dwInitSeed)
	//POINTER(pLogicalRoomInfo)
	//POINTER(pRoom)
	//POINTER(pDrlgRoomNext)
END_VISIT()

BEGIN_VISIT(D2DrlgDeleteStrc)
	//FIELD(nUnitType)
	//FIELD(nUnitGUID)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2ActiveRoomStrc)
	//OBJECT(tCoords)
	//POINTER(pRoomTiles)
	//POINTER(ppRoomList)
	//FIELD(nNumRooms)
	//POINTER(pUnitFirst)
	//POINTER(pUnitUpdate)
	//POINTER(pCollisionGrid)
	//POINTER(pDrlgRoom)
	//OBJECT(pSeed)
	//POINTER(pDrlgDelete)
	//FIELD(dwFlags)
	//POINTER(ppClients)
	//FIELD(nNumClients)
	//FIELD(nMaxClients)
	//FIELD(nTileCount)
	//FIELD(nAllies)
	//FIELD(unk0x60)
	//FIELD(nCurrentDeathIndex)
	//ARRAY(pad0x65)
	//ARRAY(nLastDeadGUIDs)
	//POINTER(pAct)
	//POINTER(pRoomNext)
END_VISIT()

BEGIN_VISIT(D2RoomTileStrc)
	//POINTER(pDrlgRoom)
	//POINTER(pLvlWarpTxtRecord)
	//FIELD(bEnabled)
	//POINTER(unk0x0C)
	//POINTER(unk0x10)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2RoomCoordListStrc)
	//ARRAY(pBox)
	//FIELD(bNode)
	//FIELD(bRoomActive)
	//FIELD(nIndex)
	//POINTER(pNext)
END_VISIT()

#if !(D2_VERSION_MAJOR >= 1 && D2_VERSION_MINOR >= 11)

BEGIN_VISIT(D2DrlgStrc)
	//POINTER(pLevel)
	//OMIT(pMempool)
	//OBJECT(hArchive)
	//POINTER(pAct)
	//FIELD(nAct)
	//ARRAY(padding0x11)
	//OBJECT(pSeed)
	//FIELD(dwStartSeed)
	//FIELD(dwGameLowSeed)
	//FIELD(dwFlags)
	//ARRAY(tStatusRoomsLists)
	//POINTER(pDrlgRoom)
	//FIELD(nRoomsInitSinceLastUpdate)
	//FIELD(nRoomsInitTimeout)
	//ARRAY(padding0x3DE)
	//FIELD(nAllocatedRooms)
	//FIELD(nFreedRooms)
	//POINTER(pGame)
	//FIELD(nDifficulty)
	//ARRAY(pad0x3ED)
	//OBJECT(pfAutomap)
	//OBJECT(pfTownAutomap)
	//FIELD(nStaffTombLevel)
	//FIELD(nBossTombLevel)
	//ARRAY(pTiles)
	//FIELD(bJungleInterlink)
	//POINTER(pWarp)
END_VISIT()

#else

BEGIN_VISIT(D2DrlgStrc)
	//ARRAY(pTiles)
	//OBJECT(pfTownAutomap)
	//POINTER(pAct)
	//FIELD(nBossTombLevel)
	//FIELD(dwStartSeed)
	//FIELD(dwGameLowSeed)
	//FIELD(nFreedRooms)
	//OMIT(pMempool)
	//ARRAY(tStatusRoomsLists)
	//FIELD(bJungleInterlink)
	//FIELD(dwFlags)
	//POINTER(pDrlgRoom)
	//OBJECT(pfAutomap)
	//FIELD(nRoomsInitTimeout)
	//ARRAY(pad0x45D)
	//OBJECT(hArchive)
	//POINTER(pGame)
	//FIELD(nAllocatedRooms)
	//POINTER(pLevel)
	//FIELD(nDifficulty)
	//FIELD(nAct)
	//FIELD(pad0x476)
	//FIELD(nRoomsInitSinceLastUpdate)
	//FIELD(nStaffTombLevel)
	//POINTER(pWarp)
	//OBJECT(pSeed)
END_VISIT()

#endif

BEGIN_VISIT(D2DrlgTileDataStrc)
	//FIELD(nWidth)
	//FIELD(nHeight)
	//FIELD(nPosX)
	//FIELD(nPosY)
	//FIELD(unk0x10)
	//FIELD(dwFlags)
	//POINTER(pTile)
	//FIELD(nTileType)
	//POINTER(unk0x20)
	//FIELD(unk0x24)
	//FIELD(nRed)
	//FIELD(nGreen)
	//FIELD(nBlue)
	//FIELD(nIntensity)
	//FIELD(unk0x2C)
END_VISIT()

BEGIN_VISIT(D2DrlgActStrc)
	//FIELD(nAct)
	//ARRAY(pad0x01)
	//POINTER(pRoom)
	//POINTER(pDrlg)
	//FIELD(dwInitSeed)
	//FIELD(nTownId)
	//POINTER(pEnvironment)
	//OBJECT(pfnActCallBack)
	//FIELD(bClient)
	//FIELD(bHasPendingRoomsUpdates)
	//FIELD(bHasPendingRoomDeletions)
	//FIELD(bHasPendingUnitListUpdates)
	//OBJECT(pTileData)
	//OMIT(pMemPool)
END_VISIT()

BEGIN_VISIT(D2DrlgAnimTileGridStrc)
	//POINTER(ppMapTileData)
	//FIELD(nFrames)
	//FIELD(nCurrentFrame)
	//FIELD(nAnimationSpeed)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2DrlgBuildStrc)
	//FIELD(nPreset)
	//FIELD(nDivisor)
	//FIELD(nRand)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2DrlgFileStrc)
	//FIELD(nSubstMethod)
	//OMIT(pDS1File)
	//FIELD(unk0x08)
	//FIELD(nWidth)
	//FIELD(nHeight)
	//FIELD(nWallLayers)
	//FIELD(nFloorLayers)
	//ARRAY(pTileTypeLayer)
	//ARRAY(pWallLayer)
	//ARRAY(pFloorLayer)
	//OMIT(pShadowLayer)
	//OMIT(pSubstGroupTags)
	//FIELD(nSubstGroups)
	//POINTER(pSubstGroups)
	//POINTER(pPresetUnit)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2DrlgTileInfoStrc)
	//FIELD(nPosX)
	//FIELD(nPosY)
	//FIELD(nTileIndex)
END_VISIT()

BEGIN_VISIT(D2DrlgLevelStrc)
	//POINTER(pDrlg)
	//FIELD(nLevelId)
	//FIELD(nLevelType)
	//FIELD(nDrlgType)
	//FIELD(dwFlags)
	//OBJECT(pSeed)
	//FIELD(dwInitSeed)
	//BEGIN_UNION()
		//FIELD(nPosX)
		//FIELD(nPosY)
		//FIELD(nWidth)
		//FIELD(nHeight)
		//OBJECT(pLevelCoords)
	//END_UNION()
	//POINTER(pFirstRoomEx)
	//FIELD(nRooms)
	//BEGIN_UNION()
		//POINTER(pPreset)
		//POINTER(pOutdoors)
		//POINTER(pMaze)
	//END_UNION()
	//POINTER(pCurrentMap)
	//FIELD(nCoordLists)
	//ARRAY(pTileInfo)
	//FIELD(nTileInfo)
	//ARRAY(nRoom_Center_Warp_X)
	//ARRAY(nRoom_Center_Warp_Y)
	//FIELD(nRoomCoords)
	//POINTER(pJungleDefs)
	//FIELD(nJungleDefs)
	//POINTER(pBuild)
	//FIELD(bActive)
	//FIELD(dwInactiveFrames)
	//POINTER(pPresetMaps)
	//POINTER(pNextLevel)
END_VISIT()

BEGIN_VISIT(D2DrlgLinkStrc)
	//OMIT(pfLinker)
	//FIELD(nLevel)
	//FIELD(nLevelLink)
	//FIELD(nLevelLinkEx)
END_VISIT()

BEGIN_VISIT(D2DrlgLevelLinkDataStrc)
	//OBJECT(pSeed)
	//ARRAY(pLevelCoord)
	//POINTER(pLink)
	//BEGIN_UNION()
		//ARRAY(nRand)
		//ARRAY(nRand2)
	//END_UNION()
	//FIELD(nIteration)
	//FIELD(nCurrentLevel)
END_VISIT()

BEGIN_VISIT(D2DrlgLinkerParamsStrc)
	//ARRAY(nLinkerLevels)
	//ARRAY(nChance)
	//FIELD(dwFlags)
END_VISIT()

BEGIN_VISIT(D2DrlgOrthStrc)
	//BEGIN_UNION()
		//POINTER(pDrlgRoom)
		//POINTER(pLevel)
	//END_UNION()
	//FIELD(nDirection)
	//ARRAY(unk0x05)
	//FIELD(bPreset)
	//FIELD(bInit)
	//POINTER(pBox)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2DrlgPresetInfoStrc)
	//POINTER(pDrlgMap)
	//FIELD(nDirection)
END_VISIT()

BEGIN_VISIT(D2DrlgRGBStrc)
	//ARRAY(unk0x00)
	//FIELD(nRed)
	//FIELD(nGreen)
	//FIELD(nBlue)
END_VISIT()

BEGIN_VISIT(D2DrlgRoomTilesStrc)
	//POINTER(pWallTiles)
	//FIELD(nWalls)
	//POINTER(pFloorTiles)
	//FIELD(nFloors)
	//POINTER(pRoofTiles)
	//FIELD(nRoofs)
END_VISIT()

BEGIN_VISIT(D2DrlgTileLinkStrc)
	//FIELD(bFloor)
	//POINTER(pMapTile)
	//POINTER(pNext)
END_VISIT()

BEGIN_VISIT(D2DrlgTileGridStrc)
	//POINTER(pMapLinks)
	//POINTER(pAnimTiles)
	//FIELD(nWalls)
	//FIELD(nFloors)
	//FIELD(nShadows)
	//OBJECT(pTiles)
END_VISIT()

BEGIN_VISIT(D2DrlgUnitsStrc)
	//ARRAY(unk0x00)
	//FIELD(bDelete)
	//FIELD(bUpdate)
	//ARRAY(unk0x2C)
	//OMIT(pMemPool)
END_VISIT()

BEGIN_VISIT(D2DrlgWarpStrc)
	//FIELD(nLevel)
	//ARRAY(nVis)
	//ARRAY(nWarp)
	//POINTER(pNext)
END_VISIT()
